from fpdf import FPDF

BRAND_COLOR = (176, 112, 80)   # Rose gold #B07050
BG_COLOR = (253, 250, 248)     # Warm white #FDFAF8
TEXT_COLOR = (26, 26, 26)


class ItineraryPDF(FPDF):
    """Custom FPDF subclass with Unmapped branding."""

    def __init__(self, trip_title: str = "Your Unmapped Trip"):
        super().__init__()
        self.trip_title = trip_title

    def header(self):
        """
        Render the page header with Unmapped branding.

        - Fill the header band with BRAND_COLOR background
        - Add the "Unmapped" wordmark in white on the left
        - Add the trip title centred in the header
        - Draw a subtle divider line below the header
        """
        # TODO: Implement branded header with set_fill_color and cell
        self.set_fill_color(*BRAND_COLOR)
        self.rect(0, 0, 210, 20, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 20, f"Unmapped  —  {self.trip_title}", align="C")
        self.ln(5)

    def footer(self):
        """
        Render the page footer with page number and attribution.

        - Position at 15mm from the bottom of the page
        - Show "Page X" centred in grey text
        - Show "Generated by Unmapped" in smaller grey text
        """
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}  |  Generated by Unmapped", align="C")


def generate_itinerary_pdf(trip_data: dict) -> bytes:
    """
    Build a full PDF itinerary from a trip data dict.

    - Instantiate ItineraryPDF with the trip destination as title
    - Add a summary page: destination, dates, travellers, estimated total cost
    - If trip_data contains "flights", add a flights summary section
    - If trip_data contains "hotels", add a hotels summary section
    - Loop through trip_data["days"] and call add_day_section() for each
    - Return the PDF as bytes (use pdf.output() with dest="S" or output())
    """
    pdf = ItineraryPDF(trip_title=trip_data.get("destination", "Your Trip"))
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # TODO: Add summary section
    # TODO: Add flights section
    # TODO: Add hotels section

    for day in trip_data.get("days", []):
        add_day_section(pdf, day)

    return bytes(pdf.output())


def add_day_section(pdf: ItineraryPDF, day: dict) -> None:
    """
    Render a single day's activities as a styled section in the PDF.

    - Add a coloured day header bar with the day number and date
    - For each activity, render: time (if present), title, description, estimated cost
    - Indent activities under the day header
    - Add a light horizontal rule after the last activity
    """
    # TODO: Implement day section rendering with FPDF cells and multi_cell
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*BRAND_COLOR)
    pdf.cell(0, 8, f"Day {day.get('day_number', '?')}  —  {day.get('date', '')}", ln=True)
    pdf.set_text_color(*TEXT_COLOR)
    pdf.set_font("Helvetica", "", 9)
    for activity in day.get("activities", []):
        label = f"  {activity.get('time', '')}  {activity.get('title', '')}"
        pdf.cell(0, 6, label, ln=True)
