from datetime import datetime as _dt

from fpdf import FPDF

BRAND_COLOR = (176, 112, 80)   # Rose gold #B07050
BG_COLOR = (253, 250, 248)     # Warm white #FDFAF8
TEXT_COLOR = (26, 26, 26)


class ItineraryPDF(FPDF):
    """Custom FPDF subclass with Unmapped branding."""

    def __init__(self, trip_title: str = "Your Unmapped Trip"):
        super().__init__()
        self.trip_title = trip_title

    def header(self):
        """
        Render the page header with Unmapped branding.

        - Fill the header band with BRAND_COLOR background
        - Add the "Unmapped" wordmark in white on the left
        - Add the trip title centred in the header
        - Draw a subtle divider line below the header
        """
        # TODO: Implement branded header with set_fill_color and cell
        self.set_fill_color(*BRAND_COLOR)
        self.rect(0, 0, 210, 20, "F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 20, f"Unmapped  —  {self.trip_title}", align="C")
        self.ln(5)

    def footer(self):
        """
        Render the page footer with page number and attribution.

        - Position at 15mm from the bottom of the page
        - Show "Page X" centred in grey text
        - Show "Generated by Unmapped" in smaller grey text
        """
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}  |  Generated by Unmapped", align="C")


def generate_itinerary_pdf(trip_data: dict) -> bytes:
    """
    Build a full PDF itinerary from a trip data dict.

    - Instantiate ItineraryPDF with the trip destination as title
    - Add a summary page: destination, dates, travellers, estimated total cost
    - If trip_data contains "flights", add a flights summary section
    - If trip_data contains "hotels", add a hotels summary section
    - Loop through trip_data["days"] and call add_day_section() for each
    - Return the PDF as bytes (use pdf.output() with dest="S" or output())
    """
    pdf = ItineraryPDF(trip_title=trip_data.get("destination", "Your Trip"))
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=20)

    # TODO: Add summary section
    # TODO: Add flights section
    # TODO: Add hotels section

    for day in trip_data.get("days", []):
        add_day_section(pdf, day)

    return bytes(pdf.output())


class ReceiptPDF(FPDF):
    def __init__(self, booking_reference: str):
        super().__init__()
        self.booking_reference = booking_reference
        self.set_margins(15, 36, 15)

    def header(self):
        self.set_fill_color(*BRAND_COLOR)
        self.rect(0, 0, 210, 28, "F")
        self.set_xy(0, 7)
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 14)
        self.cell(210, 10, "Unmapped  -  Booking Confirmation", align="C", ln=True)
        self.set_font("Helvetica", "", 9)
        self.cell(210, 9, f"Booking Reference: {self.booking_reference}", align="C", ln=True)
        self.set_y(36)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Thank you for booking with Unmapped", align="C")


def _section_header_receipt(pdf: FPDF, title: str) -> None:
    pdf.set_fill_color(*BRAND_COLOR)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 10)
    pdf.cell(0, 7, f"  {title}", fill=True, ln=True)
    pdf.set_text_color(*TEXT_COLOR)
    pdf.ln(1)


def _label_value(pdf: FPDF, label: str, value: str) -> None:
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(65, 6, label, ln=False)
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 6, value, ln=True)


def _parse_nights(check_in: str, check_out: str) -> int:
    for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y"):
        try:
            return max(1, (_dt.strptime(check_out, fmt) - _dt.strptime(check_in, fmt)).days)
        except (ValueError, TypeError):
            continue
    return 1


def _nights_for_hotel(hotel) -> int | None:
    """Derive night count from dates when available, falling back to total/rate."""
    if hotel.check_in and hotel.check_out:
        try:
            return _parse_nights(hotel.check_in, hotel.check_out)
        except Exception:
            pass
    if hotel.price_per_night_usd and hotel.price_per_night_usd > 0:
        return round(hotel.total_price_usd / hotel.price_per_night_usd)
    return None


def generate_receipt(confirm_request, booking_reference: str) -> bytes:
    """Build a booking receipt PDF and return it as bytes."""
    flights          = confirm_request.selected_flights
    hotels           = confirm_request.selected_hotels
    ground_transport = getattr(confirm_request, "selected_ground_transport", []) or []

    pdf = ReceiptPDF(booking_reference=booking_reference)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    _section_header_receipt(pdf, "Passenger Information")
    _label_value(pdf, "Name:", confirm_request.passenger_name)
    _label_value(pdf, "Email:", confirm_request.passenger_email)
    pdf.ln(5)

    # ── All flight legs ───────────────────────────────────────────────────────
    if flights:
        _section_header_receipt(pdf, "Flight Details")
        for i, flight in enumerate(flights, start=1):
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(130, 130, 130)
            route = f"{flight.leg_from} -> {flight.leg_to}" if (flight.leg_from and flight.leg_to) else ""
            if len(flights) > 1:
                pdf.cell(0, 6, f"  Leg {i}{': ' + route if route else ''}", ln=True)
            elif route:
                pdf.cell(0, 6, f"  {route}", ln=True)
            pdf.set_text_color(*TEXT_COLOR)
            _label_value(pdf, "Airline:", flight.airline)
            if flight.flight_number:
                _label_value(pdf, "Flight Number:", flight.flight_number)
            _label_value(pdf, "Departure:", flight.departure_time)
            _label_value(pdf, "Arrival:", flight.arrival_time)
            if flight.duration:
                _label_value(pdf, "Duration:", flight.duration)
            _label_value(pdf, "Stops:", "Non-stop" if flight.stops == 0 else str(flight.stops))
            _label_value(pdf, "Price:", f"${flight.price_usd:,.2f} USD")
            if i < len(flights):
                pdf.ln(3)
        pdf.ln(5)

    # ── Ground transport legs ─────────────────────────────────────────────────
    if ground_transport:
        _section_header_receipt(pdf, "Ground Transport")
        for i, gt in enumerate(ground_transport, start=1):
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(130, 130, 130)
            leg_prefix = f"Leg {i}: " if len(ground_transport) > 1 else ""
            pdf.cell(0, 6, f"  {leg_prefix}{gt.leg_from} -> {gt.leg_to}", ln=True)
            pdf.set_text_color(*TEXT_COLOR)
            _label_value(pdf, "Mode:", gt.mode.title())
            _label_value(pdf, "Operator:", gt.operator)
            _label_value(pdf, "Departure:", gt.departure_time)
            _label_value(pdf, "Arrival:", gt.arrival_time)
            _label_value(pdf, "Duration:", gt.duration)
            _label_value(pdf, "Price:", f"${gt.price_usd:,.2f} USD")
            if i < len(ground_transport):
                pdf.ln(3)
        pdf.ln(5)

    # ── All city hotels ───────────────────────────────────────────────────────
    _section_header_receipt(pdf, "Hotel Details")
    for i, hotel in enumerate(hotels, start=1):
        if len(hotels) > 1:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(130, 130, 130)
            pdf.cell(0, 6, f"  City {i}: {hotel.location}", ln=True)
            pdf.set_text_color(*TEXT_COLOR)
        _label_value(pdf, "Hotel:", hotel.name)
        _label_value(pdf, "Location:", hotel.location)
        if hotel.stars:
            _label_value(pdf, "Stars:", f"{hotel.stars} stars")
        if hotel.check_in:
            _label_value(pdf, "Check-in:", hotel.check_in)
        if hotel.check_out:
            _label_value(pdf, "Check-out:", hotel.check_out)
        nights = _nights_for_hotel(hotel)
        if nights is not None:
            _label_value(pdf, "Nights:", str(nights))
        _label_value(pdf, "Total:", f"${hotel.total_price_usd:,.2f} USD")
        if i < len(hotels):
            pdf.ln(3)
    pdf.ln(5)

    # ── Cost breakdown ────────────────────────────────────────────────────────
    _section_header_receipt(pdf, "Cost Breakdown")
    total_flights = sum(f.price_usd for f in flights)
    total_ground  = sum(gt.price_usd for gt in ground_transport)
    total_hotels  = sum(h.total_price_usd for h in hotels)
    if total_flights:
        _label_value(pdf, "Flights:", f"${total_flights:,.2f} USD")
    if total_ground:
        _label_value(pdf, "Ground Transport:", f"${total_ground:,.2f} USD")
    _label_value(pdf, "Accommodation:", f"${total_hotels:,.2f} USD")
    pdf.ln(2)
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*BRAND_COLOR)
    pdf.cell(65, 8, "Grand Total:", ln=False)
    pdf.cell(0, 8, f"${confirm_request.total_cost:,.2f} USD", ln=True)
    pdf.set_text_color(*TEXT_COLOR)

    return bytes(pdf.output())


def add_day_section(pdf: ItineraryPDF, day: dict) -> None:
    """
    Render a single day's activities as a styled section in the PDF.

    - Add a coloured day header bar with the day number and date
    - For each activity, render: time (if present), title, description, estimated cost
    - Indent activities under the day header
    - Add a light horizontal rule after the last activity
    """
    # TODO: Implement day section rendering with FPDF cells and multi_cell
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*BRAND_COLOR)
    pdf.cell(0, 8, f"Day {day.get('day_number', '?')}  —  {day.get('date', '')}", ln=True)
    pdf.set_text_color(*TEXT_COLOR)
    pdf.set_font("Helvetica", "", 9)
    for activity in day.get("activities", []):
        label = f"  {activity.get('time', '')}  {activity.get('title', '')}"
        pdf.cell(0, 6, label, ln=True)
